name: Terraform CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -out=tfplan
      env:
        AWS_REGION: us-west-2
        AWS_ROLE_ARN: arn:aws:iam::586794457112:role/GitHubActionsRole
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
      env:
        AWS_REGION: us-west-2
        AWS_ROLE_ARN: arn:aws:iam::586794457112:role/GitHubActionsRole